DECLARE @TBLNAME VARCHAR(255)
SET @TBLNAME = 'Changelly30dDailyPred'

DECLARE @CREATE_TEMPLATE VARCHAR(MAX)
SET @CREATE_TEMPLATE =
'
CREATE TABLE  {TBLNAME} (
    ID int IDENTITY(1,1) primary key,
	Crypto nvarchar(50) NOT NULL,
	Date_Pred datetimeoffset (7) NOT NULL,
	[Date] datetimeoffset (7) NOT NULL,
	Close_Price_USD decimal(20,2) NOT NULL,
	Change_perc decimal(5,2) NULL,
	DateTmModified datetimeoffset (7) default SYSDATETIMEOFFSET(),
)
CREATE UNIQUE INDEX uidx_Changelly30dDailyPred on {TBLNAME} (Date_Pred, [Date]);
'
DECLARE @SQL_SCRIPT VARCHAR(MAX)

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME=@TBLNAME AND XTYPE='U')
BEGIN
	SET @SQL_SCRIPT = REPLACE(@CREATE_TEMPLATE, '{TBLNAME}', @TBLNAME)
	EXECUTE (@SQL_SCRIPT)
END;