DECLARE @TBLNAME VARCHAR(255)
SET @TBLNAME = 'CryptoDaily'

DECLARE @CREATE_TEMPLATE VARCHAR(MAX)
SET @CREATE_TEMPLATE = 
'
CREATE TABLE  {TBLNAME} (
	Crypto nvarchar(50) NOT NULL,
	[Date] datetimeoffset (7) NOT NULL,
	Open_Price_USD decimal(20,2) NOT NULL,
	DateTmModified datetimeoffset (7) default getutcdate(),
)
CREATE UNIQUE INDEX uidx_BTC_Daily on {TBLNAME} ([Date]);
'
DECLARE @SQL_SCRIPT VARCHAR(MAX)

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME=@TBLNAME AND XTYPE='U')
BEGIN
	SET @SQL_SCRIPT = REPLACE(@CREATE_TEMPLATE, '{TBLNAME}', @TBLNAME)
	EXECUTE (@SQL_SCRIPT)
END;